// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6G52R7MdLAptbKHrNbegTQdPfRJt-4Dg',
    appId: '1:411741735226:web:0e521030a173661e2fe803',
    messagingSenderId: '411741735226',
    projectId: 'todotestfire',
    authDomain: 'todotestfire.firebaseapp.com',
    storageBucket: 'todotestfire.firebasestorage.app',
    measurementId: 'G-VG1LCV5ZFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7xqqOOXUChcNFBr39aQxyfC6Wg58Ykng',
    appId: '1:411741735226:android:c36b74ad403ebf1d2fe803',
    messagingSenderId: '411741735226',
    projectId: 'todotestfire',
    storageBucket: 'todotestfire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06sCRqNJNVXXOP1xojKa_hJFWsD-KEjY',
    appId: '1:411741735226:ios:c2c3d8557a2e5dd22fe803',
    messagingSenderId: '411741735226',
    projectId: 'todotestfire',
    storageBucket: 'todotestfire.firebasestorage.app',
    iosBundleId: 'com.example.todoTestFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA06sCRqNJNVXXOP1xojKa_hJFWsD-KEjY',
    appId: '1:411741735226:ios:c2c3d8557a2e5dd22fe803',
    messagingSenderId: '411741735226',
    projectId: 'todotestfire',
    storageBucket: 'todotestfire.firebasestorage.app',
    iosBundleId: 'com.example.todoTestFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6G52R7MdLAptbKHrNbegTQdPfRJt-4Dg',
    appId: '1:411741735226:web:428c130616f384292fe803',
    messagingSenderId: '411741735226',
    projectId: 'todotestfire',
    authDomain: 'todotestfire.firebaseapp.com',
    storageBucket: 'todotestfire.firebasestorage.app',
    measurementId: 'G-B45PYQD9N6',
  );
}
